# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-11 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('ilan_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilan_baslik', models.CharField(default='Giriş Katı 1+1 Yayla Evi', max_length=500, verbose_name='İlan başlığı')),
                ('ilan_acik', models.TextField(default='Okula yakın ', verbose_name='İlan Açıklaması')),
                ('fiyat', models.IntegerField(default=0, verbose_name='Fiyatı')),
                ('takas', models.IntegerField(choices=[(0, 'Takas Olmaz'), (1, 'Takas Olur')], default=1, verbose_name='Takas Durumu')),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
            },
        ),
        migrations.CreateModel(
            name='AltTur',
            fields=[
                ('alt_tur_id', models.AutoField(primary_key=True, serialize=False)),
                ('alt_tur_adi', models.CharField(default='Daire', max_length=50, verbose_name='Alt Türü')),
            ],
            options={
                'verbose_name': 'Alt Tür',
                'verbose_name_plural': 'Alt Türler',
            },
        ),
        migrations.CreateModel(
            name='FiyatTur',
            fields=[
                ('fiyat_tur_id', models.AutoField(primary_key=True, serialize=False)),
                ('fiyat_tur_adi', models.CharField(default='TL', max_length=10, verbose_name='Para Birimi')),
            ],
            options={
                'verbose_name': 'Fiyat Türü',
                'verbose_name_plural': 'Fiyat Türleri',
            },
        ),
        migrations.CreateModel(
            name='IcOzellik',
            fields=[
                ('ic_ozellik_id', models.AutoField(primary_key=True, serialize=False)),
                ('ic_ozellik_ismi', models.CharField(default='noob99', max_length=200, verbose_name='İç özellik ismi')),
                ('advert', models.ManyToManyField(to='estate.Advert')),
            ],
            options={
                'verbose_name': 'İç Özellik',
                'verbose_name_plural': 'İç Özellikler',
            },
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('ilce_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilce_adi', models.CharField(default='Didim', max_length=50, verbose_name='İlçe')),
            ],
            options={
                'verbose_name': 'İlçe',
                'verbose_name_plural': 'İlçeler',
            },
        ),
        migrations.CreateModel(
            name='Islem',
            fields=[
                ('islem_id', models.AutoField(primary_key=True, serialize=False)),
                ('islem_adi', models.CharField(default='Kiralık', max_length=20, verbose_name='İşlem Durumu')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
            },
        ),
        migrations.CreateModel(
            name='Kimden',
            fields=[
                ('kimden_id', models.AutoField(primary_key=True, serialize=False)),
                ('kimden_adi', models.CharField(default='Emlakçıdan', max_length=200, verbose_name='Kimden')),
            ],
            options={
                'verbose_name': 'Kimden',
                'verbose_name_plural': 'Kimden',
            },
        ),
        migrations.CreateModel(
            name='Mahallesemt',
            fields=[
                ('mahallesemt_id', models.AutoField(primary_key=True, serialize=False)),
                ('semt_adi', models.CharField(default='Mavişehir', max_length=200, verbose_name='Semt')),
                ('mahallesemt_adi', models.CharField(default='Sağtur', max_length=200, verbose_name='Mahalle')),
                ('posta_kodu', models.IntegerField(default=35330)),
                ('ilce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Ilce')),
            ],
            options={
                'verbose_name': 'Mahalle/Semt',
                'verbose_name_plural': 'Mahalle/Semtler',
            },
        ),
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('sehir_id', models.AutoField(primary_key=True, serialize=False)),
                ('sehir_adi', models.CharField(default='Aydın', max_length=50, verbose_name='İl')),
                ('plaka_kodu', models.IntegerField(default=35)),
                ('telefon_kodu', models.IntegerField(default=256)),
            ],
            options={
                'verbose_name': 'Şehir',
                'verbose_name_plural': 'Şehirler',
            },
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('tur_id', models.AutoField(primary_key=True, serialize=False)),
                ('tur_adi', models.CharField(default='Konut', max_length=50, verbose_name='Türü')),
            ],
            options={
                'verbose_name': 'Tür',
                'verbose_name_plural': 'Türler',
            },
        ),
        migrations.AddField(
            model_name='ilce',
            name='sehir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Sehir'),
        ),
        migrations.AddField(
            model_name='alttur',
            name='tur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Tur'),
        ),
        migrations.AddField(
            model_name='advert',
            name='altTur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.AltTur'),
        ),
        migrations.AddField(
            model_name='advert',
            name='fiyat_tur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.FiyatTur'),
        ),
        migrations.AddField(
            model_name='advert',
            name='ilce',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Ilce'),
        ),
        migrations.AddField(
            model_name='advert',
            name='islem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Islem'),
        ),
        migrations.AddField(
            model_name='advert',
            name='kimden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Kimden'),
        ),
        migrations.AddField(
            model_name='advert',
            name='mahallesemt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Mahallesemt'),
        ),
        migrations.AddField(
            model_name='advert',
            name='sehir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Sehir'),
        ),
        migrations.AddField(
            model_name='advert',
            name='tur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Tur'),
        ),
    ]
