# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('ilan_id', models.AutoField(primary_key=True, serialize=False)),
                ('islem_id', models.IntegerField(default=1, verbose_name='Durumu')),
                ('tur_id', models.IntegerField(default=1, verbose_name='Emlak Türü')),
                ('alt_tur_id', models.IntegerField(default=1, verbose_name='Emlak Alt-Türü')),
                ('ilan_baslik', models.CharField(default='noob', max_length=500, verbose_name='İlan başlığı')),
                ('ilan_acik', models.TextField(default='noob', verbose_name='İlan açıklaması')),
                ('fiyat_tur_id', models.IntegerField(default=0)),
                ('fiyat', models.IntegerField(default=0, verbose_name='Fiyat')),
                ('kimden_id', models.IntegerField(default=0)),
                ('sehir_id', models.IntegerField(default=0)),
                ('ilce_id', models.IntegerField(default=0)),
                ('takas', models.IntegerField(default=0)),
                ('mahallesemt_id', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'İlan',
                'verbose_name_plural': 'İlanlar',
            },
        ),
        migrations.CreateModel(
            name='AltTur',
            fields=[
                ('alt_tur_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Advert')),
            ],
        ),
        migrations.CreateModel(
            name='FiyatTur',
            fields=[
                ('fiyat_tur_id', models.AutoField(primary_key=True, serialize=False)),
                ('fiyat_tur_name', models.CharField(default='TL', max_length=10)),
                ('ilan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Advert')),
            ],
        ),
        migrations.CreateModel(
            name='Ilce',
            fields=[
                ('ilce_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilce_ismi', models.CharField(default='noob3', max_length=50)),
                ('ilan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Advert')),
            ],
        ),
        migrations.CreateModel(
            name='Islem',
            fields=[
                ('islem_id', models.AutoField(primary_key=True, serialize=False)),
                ('islem_adi', models.CharField(default='noob7', max_length=20)),
                ('ilan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Advert')),
            ],
        ),
        migrations.CreateModel(
            name='Kimden',
            fields=[
                ('kimden_id', models.AutoField(primary_key=True, serialize=False)),
                ('kimden_isim', models.CharField(default='noob6', max_length=200)),
                ('ilan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Advert')),
            ],
        ),
        migrations.CreateModel(
            name='Mahallesemt',
            fields=[
                ('mahallesemt_id', models.AutoField(primary_key=True, serialize=False)),
                ('mahallesemt_ismi', models.CharField(default='noob4', max_length=200)),
                ('semt_ismi', models.CharField(default='noob5', max_length=200)),
                ('posta_kodu', models.IntegerField(default=35330)),
                ('ilan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Advert')),
                ('ilce_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Ilce')),
            ],
        ),
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('sehir_id', models.AutoField(primary_key=True, serialize=False)),
                ('sehir_isim', models.CharField(default='noob2', max_length=50)),
                ('plaka_kodu', models.IntegerField(default=35)),
                ('telefon_kodu', models.IntegerField(default=256)),
                ('ilan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Advert')),
            ],
        ),
        migrations.CreateModel(
            name='Tur',
            fields=[
                ('tur_id', models.AutoField(primary_key=True, serialize=False)),
                ('ilan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Advert')),
            ],
        ),
        migrations.AddField(
            model_name='mahallesemt',
            name='sehir_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Sehir'),
        ),
        migrations.AddField(
            model_name='ilce',
            name='sehir_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Sehir'),
        ),
        migrations.AddField(
            model_name='alttur',
            name='tur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.Tur'),
        ),
    ]
