# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-30 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alttur',
            name='alt_tur_isim',
            field=models.CharField(default='noob10', max_length=50),
        ),
        migrations.AddField(
            model_name='tur',
            name='tur_isim',
            field=models.CharField(default='noob9', max_length=50),
        ),
    ]
