# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-15 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='lat',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='advert',
            name='long',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
